version: "3"
services:
  statistics:
    image: nadavtasher/statistics
    restart: unless-stopped    
    volumes:
      # Data volume
      - statistics_data:/opt
      # Configuration file
      - ./statistics/configuration.mjs:/project/backend/external/configuration.mjs:ro

volumes:
  statistics_data: